### ISSUE TITLE
0.2.0 source code?

### ISSUE THREAD

**Issue by CobaltCause** [apparentlymart/rust-lpc81x-hal#1]
[crates.io](https://crates.io/crates/lpc81x-hal) has a `0.2.0` version of this crate and points to this repository. However, the latest version I can find in `Cargo.toml` in this repo is `0.1.0`. Is the new version hosted in a different repo or just not publicly available?

**Comment by apparentlymart** [comment]
Hi @SoftwareSheriff,

I'm not sure exactly what I did here but I've confirmed that the source code in 0.2.0 on crates.io matches what's in the latest commit in this repository aside from the cargo metadata, and so I'm guessing that I simply failed to push the result of running the release to this repository and then tag it as v0.2.0.

In order to tidy things back up again I'm going to make a v0.2.0 tag now which has a `Cargo.toml` matching the one in the 0.2.0 release on crates.io.

Thanks for pointing this out, and sorry that it's been almost a year since I was monitoring this repository and so I didn't see your issue until now. :confounded:
